# Generated by Django 4.0.3 on 2022-05-04 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_nuestrouser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('autor', models.CharField(max_length=10, verbose_name='Emitente')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
        ),
    ]
